import blockContent from './blockContent'
import category from './category'
import post from './post'
import author from './author'
import imagesMaison from './imagesMaison'
import about from './about'
import activites from './activities'
import detailsLogement from './detailsLogement'
import detailsService from './detailsServices'
import detailsEquipementsInterieur from './detailsEquipementsInterieur'
import detailsEquipementsExterieur from './detailsEquipementsExterieur'
import detailsProximite from './detailsProximite'
import Disponibilite from './disponibilite'

export const schemaTypes = [imagesMaison, about, detailsLogement, detailsService, detailsEquipementsInterieur, detailsEquipementsExterieur, detailsProximite, activites, Disponibilite, blockContent]
